language: node_js
sudo: false
node_js:
- '10'

env:
  - NG_CLI_ANALYTICS=ci

addons:
  chrome: stable

cache:
 directories:
   - node_modules
   - $HOME/.npm

before_install:
  - npm i -g codecov

script:
  - npm run build:all
  - npm run test:all-ci

after_success:
  - codecov
