language: node_js
sudo: false
node_js:
  - '10'

env:
  global:
    - CC_TEST_REPORTER_ID=e53df554d307390611b128da0f5f0d0c6b799fa9ef767b1a011ceab8e3ebee90
    - NG_CLI_ANALYTICS=ci

addons:
  chrome: stable

cache:
  directories:
    - node_modules
    - $HOME/.npm

before_install:
  - npm i -g codecov greenkeeper-lockfile

install: npm install

before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run build:all
  - npm run test:all-ci

after_script:
  - greenkeeper-lockfile-upload
  # Pipe the coverage data to Code Climate
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.core.json coverage/core/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.data-layer.json coverage/data-layer/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.drawing-layer.json coverage/drawing-layer/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.js-marker-clusterer.json coverage/js-marker-clusterer/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.kml-layer.json coverage/kml-layer/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.places.json coverage/playces/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.shapes.json coverage/shapes/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.snazzy-info-window.json coverage/snazzy-info-window/lcov.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 8 # Sum both coverage parts into coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi # Upload coverage/codeclimate.json

after_success:
  - codecov
